name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # Still Ubuntu, but we run Amazon Linux in Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run inside Amazon Linux container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace amazonlinux:2023 bash -c "
            yum update -y && \
            yum install -y nodejs npm docker && \
            cd backend && npm install && npm run lint && npm test && \
            cd ../frontend && npm install && npm run lint && npm test
          "

      - name: Docker Build and Push (from host)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t yourdockerhub/backend:latest ./backend
          docker build -t yourdockerhub/frontend:latest ./frontend
          docker push yourdockerhub/backend:latest
          docker push yourdockerhub/frontend:latest

